version: "3.8"

services:
  wireguard:
    image: yuuki72/wg-easy
    restart: unless-stopped
    container_name: wg-vpn-server
    ports:
      - "53:53/udp"
      # - "80:80/tcp"
    expose:
      - "80"
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file: .env
    networks:
      - caddy_network

networks:
  caddy_network:
    driver: bridge
    external: true
    name: caddy_network