version: "3.8"

services:
  ovenmediaengine:
    image: airensoft/ovenmediaengine:latest
    container_name: media-engine-server
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8081:8081"
      - "9999:9999"
      - "3333:3333"
      - "10000-10009:10000-10009"
    expose:
      - "1935"
      - "8081"
      - "9999"
      - "3333"
      - "10000-10009"
    volumes:
     - ./bin/origin_conf/Server.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml:ro
     - ./bin/edge_conf/Server.xml:/opt/ovenmediaengine/bin/edge_conf/Server.xml:ro
    #   - /var/log/ovenmediaengine:/var/log/ovenmediaengine
    environment:
      - OME_HOST_IP=192.168.1.254
      # - OME_HTTP_PORT=8080
      # - OME_HTTPS_PORT=8443
    networks:
      - caddy_network
  ovenmediaplayer:
    image: airensoft/ovenplayerdemo:latest
    container_name: media-player-server
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
    - caddy_network

networks:
  caddy_network:
    driver: bridge
    external: true
    name: caddy_network